const cities = [ 
    'Rio Branco', 
    'Macapá', 
    'Maceió', 
    'Manaus', 
    'Salvador', 
    'Fortaleza', 
    'Brasília', 
    'Vitória', 
    'Goiânia', 
    'São Luís', 
    'Cuiabá', 
    'Campo Grande', 
    'Belo Horizonte', 
    'Belém', 
    'João Pessoa', 
    'Curitiba', 
    'Recife', 
    'Teresina', 
    'Rio de Janeiro', 
    'Natal', 
    'Porto Alegre', 
    'Porto Velho', 
    'Boa Vista', 
    'Florianópolis', 
    'São Paulo', 
    'Aracaju', 
    'Palmas'
]

export default cities